from pathlib import Path
import shutil

killer_perks = {
    "aNursesCalling",
    "agitation",
    "alienInstinct",
    "allShakingThunder",
    "awakenedAwareness",
    "bamboozle",
    "barbecueAndChilli",
    "batteriesIncluded",
    "beastOfPrey",
    "bitterMurmur",
    "bloodEcho",
    "bloodWarden",
    "bloodhound",
    "brutalStrength",
    "callOfBrine",
    "corruptIntervention",
    "coulrophobia",
    "coupDeGr%C3%A2ce",
    "cruelLimits",
    "darkArrogance",
    "darkDevotion",
    "darknessRevealed",
    "deadMansSwitch",
    "deathbound",
    "deerstalker",
    "discordance",
    "dissolution",
    "distressing",
    "Dominance",
    "dragonsGrip",
    "dyingLight",
    "enduring",
    "eruption",
    "fireUp",
    "forcedHesitation",
    "forcedPenance",
    "foreverEntwined",
    "franklinsDemise",
    "friendsTilTheEnd",
    "furtiveChase",
    "gameAfoot",
    "gearhead",
    "geneticLimits",
    "grimEmbrace",
    "haywire",
    "helpWanted",
    "hexBloodFavour",
    "hexCrowdControl",
    "hexDevourHope",
    "hexFaceTheDarkness",
    "hexHauntedGround",
    "hexHuntressLullaby",
    "hexNoOneEscapesDeath",
    "hexNothingButMisery",
    "hexPentimento",
    "hexRetribution",
    "hexRuin",
    "hexTheThirdSeal",
    "hexThrillOfTheHunt",
    "hexTwoCanPlay",
    "hexUndying",
    "HexWretchedFate",
    "hoarder",
    "hubris",
    "HumanGreed",
    "hysteria",
    "imAllEars",
    "infectiousFright",
    "insidious",
    "ironGrasp",
    "ironMaiden",
    "knockOut",
    "languidTouch",
    "lethalPursuer",
    "leverage",
    "lightborn",
    "machineLearning",
    "madGrit",
    "makeYourChoice",
    "mercilessStorm",
    "mindbreaker",
    "monitorAndAbuse",
    "nemesis",
    "noQuarter",
    "noWayOut",
    "noneAreFree",
    "nowhereToHide",
    "oppression",
    "overcharge",
    "overwhelmingPresence",
    "phantomFear",
    "playWithYourFood",
    "popGoesTheWeasel",
    "predator",
    "rancor",
    "rapidBrutality",
    "rememberMe",
    "saveTheBestForLast",
    "scourgeHookFloodsOfRage",
    "scourgeHookHangmansTrick",
    "scourgeHookJaggedCompass",
    "scourgeHookMonstrousShrine",
    "scourgeHookPainResonance",
    "septicTouch",
    "shadowborn",
    "shatteredHope",
    "sloppyButcher",
    "spiesFromTheShadows",
    "spiritFury",
    "starstruck",
    "stridor",
    "superiorAnatomy",
    "surge",
    "surveillance",
    "terminus",
    "territorialImperative",
    "thanatophobia",
    "thrillingTremors",
    "thwack",
    "tinkerer",
    "trailOfTorment",
    "ultimateWeapon",
    "unbound",
    "undone",
    "unforeseen",
    "unnervingPresence",
    "unrelenting",
    "weaveAttunement",
    "whispers",
    "zanshinTactics",
}

base = Path("perks")
(base / "killer").mkdir(exist_ok=True)
(base / "survivor").mkdir(exist_ok=True)

moved_killer = 0
moved_survivor = 0

for png in base.glob("*.png"):
    perk_name = png.stem

    if perk_name in killer_perks:
        shutil.move(str(png), str(base / "killer" / png.name))
        moved_killer += 1
    else:
        shutil.move(str(png), str(base / "survivor" / png.name))
        moved_survivor += 1

print(f"Killer perks moved: {moved_killer}")
print(f"Survivor perks moved: {moved_survivor}")